"""initial schema

Revision ID: 4bc037ad74e0
Revises: 
Create Date: 2026-07-13 18:06:04.463362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bc037ad74e0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adjudication_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_name', sa.String(), nullable=False),
    sa.Column('candidate_description', sa.String(), nullable=True),
    sa.Column('retrieved_neighbors', sa.String(), nullable=True),
    sa.Column('model_decision', sa.String(), nullable=True),
    sa.Column('model_confidence', sa.Float(), nullable=True),
    sa.Column('model_reasoning', sa.String(), nullable=True),
    sa.Column('human_resolution', sa.String(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('concepts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('goal_tags', sa.String(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_reinforced', sa.DateTime(), nullable=True),
    sa.Column('embedding_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_path', sa.String(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), nullable=True),
    sa.Column('extracted_concepts', sa.String(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('concept_requirements', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opportunities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('skill_match_pct', sa.Float(), nullable=True),
    sa.Column('missing_skills', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('proficiency', sa.Float(), nullable=True),
    sa.Column('last_used', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('merge_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_name', sa.String(), nullable=False),
    sa.Column('candidate_category', sa.String(), nullable=True),
    sa.Column('matched_concept_id', sa.Integer(), nullable=True),
    sa.Column('llm_confidence', sa.Float(), nullable=True),
    sa.Column('llm_reasoning', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['matched_concept_id'], ['concepts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('merge_queue')
    op.drop_table('skills')
    op.drop_table('opportunities')
    op.drop_table('goals')
    op.drop_table('content_log')
    op.drop_table('concepts')
    op.drop_table('adjudication_log')
    # ### end Alembic commands ###
